Able to assign `host` and `port` for emualtor
invertase/dart_firebase_admin pull request #35
Opened 2024-06-07 07:58 UTC by hn12404988

Beside setting the `host` and `port`. The `useEmulator` function is still functioning the same.

2024-06-07 07:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/dart_firebase_admin?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/dart_firebase_admin?pullRequest=35) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/dart_firebase_admin?pullRequest=35) it.</sub>

2024-06-07 10:52 UTC, Ehesp commented
Hey thanks for this contribution.

The admin SDKs don't set the host/port directly like the client SDKs, instead they read from a environment variable, see https://firebase.google.com/docs/emulator-suite/connect_auth#admin_sdks

We should probably instead parse this value if it exists and pass it through.

2024-07-08 05:34 UTC, rrousselGit commented
>  I notice you has the "do_not_use_environment" lint rule set.

That's not the same "enrivonment". We're talking about using `Platform.environment`. Using `String.fromEnvironment` is completely unrelated.

Also, this would need testing :)

2024-07-08 05:35 UTC, rrousselGit requested changes
Cf above

2024-07-10 08:40 UTC, hn12404988 commented
Hi @rrousselGit , thanks for the feedback.
I tried to fix the point you mentioned and implemented the tests. Let me know if any issue.
Thanks for the review!

2024-07-10 09:24 UTC, rrousselGit commented on packages/dart_firebase_admin/lib/src/app/emulator.dart
> +        Platform.environment['FIREBASE_AUTH_EMULATOR_HOST']!,
Could you remove this `!`?

This is possible by doing something like:

```dart
final env = Platform.environment['FIREBASE_AUTH_EMULATOR_HOST'];
if (env != null) {...}
else {...}
```

2024-07-10 09:24 UTC, rrousselGit commented on packages/dart_firebase_admin/lib/src/app/emulator.dart
> +        Platform.environment['FIRESTORE_EMULATOR_HOST']!,
Same here

2024-07-10 09:24 UTC, rrousselGit commented on packages/dart_firebase_admin/lib/src/app/emulator.dart
> +
```suggestion
```

2024-07-10 09:28 UTC, rrousselGit commented on packages/dart_firebase_admin/lib/src/app/firebase_admin.dart
> +  }) {
Wouldn't a simpler API be this?

```dart
void useAuthEmulator([Uri? uri])
```

We can then remove that `Emulator` class.

2024-07-10 09:29 UTC, rrousselGit commented on packages/dart_firebase_admin/lib/src/app/firebase_admin.dart
> +    emulator ??= Emulator.auth();
I'd rather have the environment logic directly in here, instead of a constructor inside a separate Emulator class.

2024-12-29 10:15 UTC, closed without merging